# Language flags
language: elixir

# OS matrix
os:
  - linux

# Matrix modifications.
jobs:
  include:
    - otp_release: 22.0
      elixir: 1.9
    - otp_release: 22.0
      elixir: 1.8
    - otp_release: 21.0
      elixir: 1.8
    - otp_release: 21.0
      elixir: 1.7
    - otp_release: 21.0
      elixir: 1.6
    - otp_release: 20.0
      elixir: 1.8
    - otp_release: 20.0
      elixir: 1.7
    - otp_release: 20.0
      elixir: 1.6

before_install:
  - curl https://sh.rustup.rs -sSf | sh -s -- -y

install:
  - mix local.rebar --force
  - mix local.hex --force

before_script:
  - mix deps.get

script:
  - source $HOME/.cargo/env
  - mix test --trace
